### ISSUE TITLE
✨ 可不可以增加一个账号密码登录的功能～

### ISSUE THREAD

**Issue by Liar1995** [lulu-ls/cloud-uploader#11]
hi ✨ 可不可以增加一个账号密码登录的功能～

**Comment by lulu-ls** [comment]
同学 有什么不能扫码的场景吗？ 我想下是否有必要增加这个功能

**Comment by Liar1995** [comment]
😂是这样想给别人上传云盘音乐，但是又没有即时通讯，留言的形式告诉我账号密码，就尴尬～ 还有那个刷歌，会有刷歌完成的状态吗？昨天一直在loading，然后今天看了下听歌数据似乎没有变化。QQ群还在维护吗，申请加群

**Comment by lulu-ls** [comment]
刷完歌会展示个小对勾的，你这种 loading 可能中间报错了，后边优化下

**Comment by lulu-ls** [comment]
刷完歌会展示个小对勾的，你这种 loading 可能中间报错了，后边优化下

**Comment by lulu-ls** [comment]
至于登录问题，一开始我考虑账号密码是没有扫码安全的，所以就没加。如果要接手机号登录，也是可能会以手机号、验证码的方式接入，不知道能不能解决你的问题。毕竟我也是调用第三方sdk来实现登录的，直接暴露用户的账号和密码会有一定风险。如果还有用户反馈的话，我会考虑增加账号密码登录的功能 感谢反馈

**Comment by lulu-ls** [comment]
有优化刷歌问题，已经发布了，可以重新下载试试

**Comment by Liar1995** [comment]
棒棒 感谢你的认真答复 👍

**Comment by lulu-ls** [comment]
最近又有人反馈需要这个账号密码登录的功能，已在 1.2.0 版本增加，同学可以试试，最后感谢你的反馈。如果有任何问题，可以在提给我 💯
