### ISSUE TITLE
可以打包出一个.deb文件嘛?我是Linux系统

### ISSUE THREAD

**Issue by Kun1605** [lulu-ls/cloud-uploader#12]
可以打包出一个.deb文件嘛?我是Linux系统

**Comment by lulu-ls** [comment]
晚上有时间我会更新下

**Comment by Kun1605** [comment]
好的我去找找看,谢谢~

**Comment by Kun1605** [comment]
![image](https://user-images.githubusercontent.com/19654613/171092644-84752f9d-c1b9-4562-9111-16c4fc0e665f.png)
可以正常使用~

**Comment by lulu-ls** [comment]
好的 谢谢反馈 👍
