### ISSUE TITLE
设计了一个图标

### ISSUE THREAD

**Issue by Lucas04-nhr** [lulu-ls/cloud-uploader#153]
自己设计并替换了原来应用的图标使之更符合macOS的图标设计规范，也更符合云音乐的配色。

只是动了这个部分就没有Clone下来提pr了 :-)

效果图：
<img width="836" alt="image" src="https://github.com/lulu-ls/cloud-uploader/assets/117806313/ff5ad4af-9acc-4950-ab18-5577d319d33a">

各类型文件的压缩包：
[icon.zip](https://github.com/lulu-ls/cloud-uploader/files/13935456/icon.zip)

**Comment by LuShan123888** [comment]
👍

**Comment by lulu-ls** [comment]
图标已被采纳，1.3.5 版本， 申请把你拉入贡献者了  感谢参与本项目
