### ISSUE TITLE
请问可以增加ncm格式转flac或者mp3吗？

### ISSUE THREAD

**Issue by ma3252788** [lulu-ls/cloud-uploader#26]
刚刚发现网易云下载的音乐有ncm格式，但是直接上传提示没有可上传的文件，请问能否增加自动ncm转完格式之后上传呀？

**Comment by lulu-ls** [comment]
升级到 1.2.1 版本，增加了 ncm 格式的支持

**Comment by lulu-ls** [comment]
这个晚上回去看看

**Comment by lulu-ls** [comment]
同学有没有稳定重现的方法呢   我这测试不出来

**Comment by lulu-ls** [comment]
感谢反馈 刚发布的 1.2.2 版本修复了一些崩溃问题，你可以下载试试

**Comment by lulu-ls** [comment]
更新试试，先关了后边如果有任何问题再提 感谢
