### ISSUE TITLE
能增加一个代理功能吗？在公司的时候没有代理是无法打开软件的，在家是可以正常使用的

### ISSUE THREAD

**Issue by dpeng** [lulu-ls/cloud-uploader#29]

**Comment by lulu-ls** [comment]
你的代理开成系统代理 或者全局代理 应该就可以的

**Comment by dpeng** [comment]
不行的，electron好像不走系统代理，然后在terminal里面设置代理，包括在config.ini里面设置代理好像都不生效，不知道怎么回事，可能要程序在调用electron的时候把代理设置进去才可以？

**Comment by lulu-ls** [comment]
![image](https://user-images.githubusercontent.com/28334630/179650736-b6285824-2cdc-45ab-8de6-8593e6029e8f.png)
看了下  [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 的代码，如果你得代理不需要认证是可以的，我加个输入 ip端口 的地方就行 这样能满足你得需求不

**Comment by dpeng** [comment]
> 
代理不需要认可，期待这个新功能，或者能先给我一个代码片段吗？我先拷贝到本地，自己编译运行？
太感谢了

**Comment by lulu-ls** [comment]
![image](https://user-images.githubusercontent.com/28334630/179904517-e01ec441-df8e-42c6-b02b-e0ba20ccdb3b.png)

**Comment by lulu-ls** [comment]
可以把http代理的 ip 和端口给我

**Comment by lulu-ls** [comment]
![image](https://user-images.githubusercontent.com/28334630/179904660-b9fab219-6fa5-46a4-8447-86b0c4ba7aa8.png)

**Comment by dpeng** [comment]
135.251.187.33:8080

**Comment by dpeng** [comment]
> https://note.youdao.com/s/SizptL4 这里如果下载不了，给个邮箱，我发给你

可以下载，多谢兄弟，等回公司试一下

**Comment by lulu-ls** [comment]
1.3.0 版本增加了代理功能，目前考虑到有需求的用户并不是很多，所以没做前端配置，可以通过修改const.js 下的 PROXY_ADDRESS 来实现代理，但是需要自己打包了，如果有需要可以 clone 一份试试，有什么问题可以给我反馈，issues 我现关了

**Comment by dpeng** [comment]
> https://note.youdao.com/s/SizptL4 这里如果下载不了，给个邮箱，我发给你
你有道发给我的这个版本可以工作，谢谢兄弟

等会clone一份自己编译在试试。

**Comment by dpeng** [comment]
> 

自己修改配置文件，npm run start也可以正常工作，多谢，这个issue可以关掉了

再次感谢
