### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by CCcn** [lulu-ls/cloud-uploader#33]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/23622846/179702108-7dda7d8f-9427-480a-98e1-4c44b513b65f.png">

I've already tried to restart App.

System info:
```sh
Device Type: MacBookPro11,4
System Version: Version 12.4 (Build 21F79)
System Language: en
WeChat Version: [2022-01-08 16:52:13] v3.4.1.16 (21939) #cd60ac7344 
WeChat Language: en
Historic Version: [2022-04-23 14:46:22] v3.4.0.16 (21723) #52902d22f8
Network Status: Reachable via WiFi or Ethernet
Display: *(1440x900)/Retina

```

**Comment by lulu-ls** [comment]
I'll check this weekend

**Comment by CCcn** [comment]
Thanks a lot! ！！

Waiting for your good news!

**Comment by lulu-ls** [comment]
Could you please provide the problem recurrence process and data? I can't test it
