### ISSUE TITLE
批量上传卡住不动

### ISSUE THREAD

**Issue by jony4** [lulu-ls/cloud-uploader#4]
批量拖拽到上传框后，有任务了。但是一直不上传。

**Comment by lulu-ls** [comment]
是部分上传成功，还是全部都上传不了呢？

**Comment by jony4** [comment]
全部不动的状态

**Comment by jony4** [comment]
单个上传时候没问题，很快就传上去了

**Comment by lulu-ls** [comment]
目前已知问题是，批量上传 部分成功，这个应该是网易云接口频率限制，周末我会修下。全都不动可能是哪里报错了，你有开发基础的话，可以自己本地跑下代码，开启调试模式，然后看下

**Comment by jony4** [comment]
OK 谢谢

**Comment by daluozha** [comment]
@lulu-ls 上传失败的错误信息：

UploaderWindow Fri May 13 2022 11:38:03 GMT+0800 (中国标准时间) 上传失败, error:  {
  status: 404,
  body: { msg: 'rep create failed', code: 404 },
  cookie: []
}

**Comment by lulu-ls** [comment]
好的 周末我看下

**Comment by daluozha** [comment]
感觉是api的限流问题，我不能稳定重现 bug，感觉可以将报错的 log 弹窗显示出来，方便之后提 issue 的错误追踪。

@lulu-ls 欢迎 pr 的话，我挺乐意帮忙维护的 🙋‍♂️

**Comment by lulu-ls** [comment]
欢迎，这块不是没考虑过，我是觉得直接弹出错误对用户可能不够友好（不懂代码的根本看不懂），特别是像这种上传失败，可能一次很多条都会报错

**Comment by lulu-ls** [comment]
上边的问题，有看过 NeteaseCloudMusic 的API ，没有得到答案，下边两个 issues :
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1332 // 报错问题
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/108 // 频率问题

目前上传间隔是 1 秒一次（我参考的windows版网易云上传，不清楚人家自己是不是做了啥处理），但是对于我们这种接口调用的方式，可能是有点快的，所以我才猜测降低频率应该能避免部分问题

**Comment by lulu-ls** [comment]
前两天做了更新，现在上传间隔改为 1s-3s 随机时间，自测50首没问题，你可以再测测，有啥问题麻烦再反馈下，或者你已经修了，也欢迎提交 PR，谢谢 🥇

**Comment by lulu-ls** [comment]
暂时无反馈的话，我先关了，如果有啥问题后边再提  谢谢 👍

**Comment by jony4** [comment]
好的呢，最近没看gh，有时间测试一把，谢谢！
