### ISSUE TITLE
上传bug

### ISSUE THREAD

**Issue by kekekezi** [lulu-ls/cloud-uploader#41]
上传每次重启第一次能上传 后面上传一直在loading
uploader 版本 1.3
macos 12.1

**Comment by lulu-ls** [comment]
我周末看下

**Comment by lulu-ls** [comment]
可以提供详细一点的测试流程吗？  并不能复现这个问题

**Comment by lulu-ls** [comment]
我先关了，我这边测试正常，如果有更详细的稳定复现操作流程，可以重开  谢谢
