### ISSUE TITLE
command+Q 无法退出

### ISSUE THREAD

**Issue by shuosiw** [lulu-ls/cloud-uploader#45]
系统版本：macOS 10.15.7
问题：

1. 在软件界面上无法通过 command + Q 快捷键彻底退出
2. 点击左上角关闭按钮后，实际上还在后台运行

目前只能通过以下两种方式处理，十分不便：

* 进入 **强制退出** 找到 cloud-uploader 强杀
* 进入命令行界面找到所有进程 kill：

    ```
    ps aux | grep [u]ploader | awk '{print $2}' | xargs kill
    ```

**Comment by lulu-ls** [comment]
可以试试在任务栏右击图标点退出

**Comment by shuosiw** [comment]
> 可以试试在任务栏右击图标点退出

这种方式可以退出..不过还是希望能支持快捷键hah

**Comment by lulu-ls** [comment]
感谢反馈  周末如果有时间会考虑更新一版，到时候戳你

**Comment by lulu-ls** [comment]
更新到 1.3.1 试试

**Comment by shuosiw** [comment]
@lulu-ls 测试验证过了，没问题，👍
