### ISSUE TITLE
刷歌一直转圈，并且会闪退

### ISSUE THREAD

**Issue by Karo07** [lulu-ls/cloud-uploader#47]

**Comment by lulu-ls** [comment]
有没有详细的报错信息或者稳定的复现流程呢？

**Comment by Karo07** [comment]
> 有没有详细的报错信息或者稳定的复现流程呢？

没有报错信息，打开程序后自动执行了签到和刷歌，签到可以正常完成，刷歌无限转圈，运行大概10来分钟就闪退了

**Comment by lulu-ls** [comment]
退出重新登录试试，如果还不行，那可能要打开调试模式看下输出啥错误没

**Comment by lulu-ls** [comment]
请更新到 1.3.2 试试
