### ISSUE TITLE
好像不能刷歌了

### ISSUE THREAD

**Issue by KevinLiu1995** [lulu-ls/cloud-uploader#49]
签到与刷歌都卡在loading

**Comment by KevinLiu1995** [comment]
<img width="232" alt="image" src="https://user-images.githubusercontent.com/18683637/185539877-f6c2d051-1d91-4436-a56c-142ce57962da.png">
一直转圈

**Comment by KevinLiu1995** [comment]
v1.3.1

**Comment by lulu-ls** [comment]
我下班看下，有尝试退出登录试试吗

**Comment by KevinLiu1995** [comment]
> 我下班看下，有尝试退出登录试试吗 

退出有试过，不行,1.3.0可以用，我是macOs
13不知道有没有影响

**Comment by lulu-ls** [comment]
请更新到 1.3.2 试试

**Comment by KevinLiu1995** [comment]
> 请更新到 1.3.2 试试

可以了，牛皮🍺

**Comment by jinzhongxu** [comment]
可以了牛皮
