### ISSUE TITLE
你好，这个工程用什么打开运行

### ISSUE THREAD

**Issue by jj89757hhb** [lulu-ls/cloud-uploader#55]
你好，这个工程用什么打开运行

**Comment by lulu-ls** [comment]
本地装好 nodejs 和 npm，然后看 readme 使用方法第 2 步就行，编辑工具无所谓的，我是用的 vscode

**Comment by jj89757hhb** [comment]
> 

npm run dev 这个好像不能运行？

**Comment by lulu-ls** [comment]
npm run start
