### ISSUE TITLE
关于刷歌的建议

### ISSUE THREAD

**Issue by dpeng** [lulu-ls/cloud-uploader#58]
刚刚在浏览NeteaseCloudMusicApi发现在获取歌单的时候，是否可以把“/recommend/resource”改成“/personalized/newsong”？这样每天就三百首就够了，不用担心有听过的歌曲导致刷不够。

只是个想法，不知道是否可行

**Comment by lulu-ls** [comment]
看了下文档 应该可以的， 老哥考虑下 提个 pr ？  我只能周末再研究了

**Comment by dpeng** [comment]
> 
只会写C，汇编的古董级程序员，不太懂JS，等我PR估计要很长时间，哈哈，还是等您这边的尝试吧。。。

**Comment by lulu-ls** [comment]
这个接口我测过了，目前最多只能获取 100 首，还不能分页，所以直接使用这个 api 是有一些问题的，暂时先关了，后边发现更好的方案了 戳你
