### ISSUE TITLE
不能上传 .ape 无损音频

### ISSUE THREAD

**Issue by hubandad** [lulu-ls/cloud-uploader#69]
Hi buddy,

我发现这个工具不能上传  .ape 无损音频 ， 请问是网易云的限制，还是技术限制呢？

**Comment by lulu-ls** [comment]
是程序限制的，/src/common/tools.js
<img width="348" alt="image" src="https://user-images.githubusercontent.com/28334630/194210608-eb72b878-7e2d-4e54-a6f8-53a603ebe29f.png">

**Comment by lulu-ls** [comment]
把你的类型加进去，打个包就行

**Comment by lulu-ls** [comment]
试试 1.3.3

**Comment by hubandad** [comment]
Thanks buddy.
