### ISSUE TITLE
不能刷歌了

### ISSUE THREAD

**Issue by nakupenda178** [lulu-ls/cloud-uploader#84]
版本:mac intel版的1.3.3
现象:同步中 和 正在刷歌 2个功能一直卡loading
<img width="490" alt="image" src="https://user-images.githubusercontent.com/12322144/204169074-0d89eac0-73f0-45ff-8869-bb5aeb1d2296.png">
可能原因:网易云api不可用还是怎么?没有日志也不确定

**Comment by lulu-ls** [comment]
周末我看看

**Comment by lulu-ls** [comment]
接口应该没问题，我这边测试正常，先关了，后边如果有进展给你反馈
